// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkqRzJj13gQX8xtMbmGpQMAKqwlfnJKxc',
    appId: '1:138958298199:web:ceb41f4f6119cff4c2d712',
    messagingSenderId: '138958298199',
    projectId: 'chatappflutter-60956',
    authDomain: 'chatappflutter-60956.firebaseapp.com',
    storageBucket: 'chatappflutter-60956.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzuxIgp6wgFTi0LRaqMRHtwsViUv4ZOis',
    appId: '1:138958298199:android:d1bf69fc19edbbd0c2d712',
    messagingSenderId: '138958298199',
    projectId: 'chatappflutter-60956',
    storageBucket: 'chatappflutter-60956.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlgD3LyFa9lQ0gJGJcGCsevJzBbPyzqFM',
    appId: '1:138958298199:ios:86e080447093ffcac2d712',
    messagingSenderId: '138958298199',
    projectId: 'chatappflutter-60956',
    storageBucket: 'chatappflutter-60956.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlgD3LyFa9lQ0gJGJcGCsevJzBbPyzqFM',
    appId: '1:138958298199:ios:9ca9cf0131704be8c2d712',
    messagingSenderId: '138958298199',
    projectId: 'chatappflutter-60956',
    storageBucket: 'chatappflutter-60956.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
